version: '3'

services:

  web:
    build: .
    restart: always
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - db
      - redis  # добавляем зависимость от сервиса Redis
    volumes:
      - .:/app/

  redis:
    image: "redis:alpine"  # используем образ Redis Alpine
    ports:
      - "6379:6379"  # прокидываем порт Redis

  db:
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
       - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust

volumes:
  postgres_data:
