# Generated by Django 5.0.7 on 2024-07-11 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_emailaccount_emailmessage_remove_order_items_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailAccount',
        ),
        migrations.RenameField(
            model_name='emailmessage',
            old_name='body',
            new_name='message_body',
        ),
    ]
